### ISSUE TITLE
Unable to access user filesystem

### ISSUE THREAD

**Issue by unholyeyebrows** [flathub/nl.openoffice.bluefish#1]
Hi. I am running Bluefish 2.2.10 on Fedora 28 Workstation installed from Flathub. 

When loading or saving files in Bluefish the file chooser dialogue suggests I am in my home directory but none of my existing files or folders appear. Likewise if I save a file from Bluefish into my home directory and then view that directory using Gnome's file manager, that file is not there.

From what I can tell the home folder Bluefish presents is within the flatpak container rather than my actual home folder on the Fedora filesystem. Can this be fixed as currently Bluefish is not very useful.

Thanks
Nick

**Comment by TingPing** [comment]
`flatpak override --user --filesystem=home nl.openoffice.bluefish` is an immediate solution.

**Comment by nedrichards** [comment]
Fixed by https://github.com/flathub/nl.openoffice.bluefish/commit/ee01024a2dce62b1a4d9692058e99db95be851f2
